version: '3'
services:
  event_sauce_db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sauce
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  event_sauce_mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  event_sauce_mongo_viewer:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@event_sauce_mongo:27017/