version: '3'
services:
  event_sauce_db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sauce
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - "5433:5432"