name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-nuget:
    name: Deployment

    runs-on: ubuntu-22.04

    steps:
    - name: Set version tag
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})

    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build NuGet
      run: dotnet pack -c Release -o out --version-suffix ${{ steps.vars.outputs.tag }}

    - name: Deploy NuGet Core Binaries
      run: dotnet nuget push out/EventSauce.${{ steps.vars.outputs.tag }}.nupkg -k ${{ secrets.CICD_KEY }} -s https://api.nuget.org/v3/index.json

    - name: Deploy NuGet Extension Binaries
      run: dotnet nuget push out/EventSauce.Extensions.Microsoft.DependencyInjection.${{ steps.vars.outputs.tag }}.nupkg -k ${{ secrets.CICD_KEY }} -s https://api.nuget.org/v3/index.json

    - name: Deploy NuGet Postgre Binaries
      run: dotnet nuget push out/EventSauce.Postgre.${{ steps.vars.outputs.tag }}.nupkg -k ${{ secrets.CICD_KEY }} -s https://api.nuget.org/v3/index.json

    - name: Deploy NuGet MongoDB Binaries
      run: dotnet nuget push out/EventSauce.MongoDB.${{ steps.vars.outputs.tag }}.nupkg -k ${{ secrets.CICD_KEY }} -s https://api.nuget.org/v3/index.json