name: PR Testing

on: pull_request

jobs:
  run-tests:
    name: Testing

    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sauce
        ports:
        - 5432:5432
      mongodb:
        image: mongo:5.0.3
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Run dotnet tests
      run: dotnet test
